services:
  db:
    image: pgvector/pgvector:0.8.2-pg18-trixie
    container_name: postgres
    environment:
      POSTGRES_USER: edu_admin
      POSTGRES_PASSWORD: 12345678
      PGDATA: /data/postgres
    volumes:
      - db:/data/postgres
    ports:
      - "65432:5432"
    networks:
      - net

  web:
    image: ${DOCKER_REGISTRY-}educhatbot-mvc
    container_name: educhatbot_mvc
    build:
      context: .
      dockerfile: PresentationLayer/Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=educhatbot_db;Username=edu_admin;Password=12345678;Include Error Detail=true
      - OpenAI__ApiKey=sk-proj-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
    depends_on:
      - db
    networks:
      - net

networks:
  net:
    driver: bridge

volumes:
  db:
