services:
  db:
    image: pgvector/pgvector:0.8.2-pg18-trixie
    container_name: educhatai_postgres
    environment:
      POSTGRES_USER: edu_admin
      POSTGRES_PASSWORD: 12345678
      POSTGRES_DB: educhatai_db
      PGDATA: /data/postgres
    restart: unless-stopped
    volumes:
      - db:/data/postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U edu_admin -d educhatai_db"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s
    networks:
      - net

  redis:
    image: redis:7-alpine
    container_name: educhatai_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 10
    networks:
      - net

  redis-ui:
    image: redis/redisinsight:latest
    container_name: educhatai_redis_ui
    restart: unless-stopped
    ports:
      - "5540:5540"
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - net

  web:
    image: ${DOCKER_REGISTRY-}educhatai-aspnetcore
    container_name: educhatai_web
    build:
      context: .
      dockerfile: PresentationLayer/Dockerfile
    restart: unless-stopped
    ports:
      - "8080:8080"
    env_file:
      - path: .env
        required: false
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_HTTP_PORTS: 8080
      HttpsRedirection__Enabled: false
      ConnectionStrings__Database: Host=db;Port=5432;Database=educhatai_db;Username=edu_admin;Password=12345678;Include Error Detail=true
      Redis__ConnectionString: redis:6379
      AI__Ollama__Endpoint: http://ollama:11434
      AppBaseUrl: http://localhost:8080
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - net

  ollama:
    image: ollama/ollama
    container_name: educhatai_ollama
    restart: unless-stopped
    ports:
      - "11434:11434"
    volumes:
      - ollama:/root/.ollama
    networks:
      - net

networks:
  net:
    driver: bridge

volumes:
  db:
  ollama:
