services:
  db:
    image: pgvector/pgvector:0.8.2-pg18-trixie
    container_name: postgres
    environment:
      POSTGRES_USER: edu_admin
      POSTGRES_PASSWORD: 12345678
      POSTGRES_DB: educhatbot_db
      PGDATA: /data/postgres
    volumes:
      - db:/data/postgres
    ports:
      - "65432:5432"
    networks:
      - net

  redis:
    image: redis:7-alpine
    container_name: educhatbot_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - net

  redis-ui:
    image: redis/redisinsight:latest
    container_name: educhatbot_redis_ui
    restart: unless-stopped
    ports:
      - "5540:5540"
    networks:
      - net
    depends_on:
      - redis

  web:
    image: ${DOCKER_REGISTRY-}educhatbot-mvc
    container_name: educhatbot_mvc
    build:
      context: .
      dockerfile: PresentationLayer/Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=educhatbot_db;Username=edu_admin;Password=12345678;Include Error Detail=true
      - OpenAI__ApiKey=sk-proj-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
      - Redis__ConnectionString=redis:6379
    depends_on:
      - db
      - redis
    networks:
      - net

networks:
  net:
    driver: bridge

volumes:
  db:
